/**
 * Rule Catalog — complete catalog of 88 governance rules.
 *
 * Organized into 7 categories:
 *   1. media_plan     — Media plan alignment rules (R001-R008)
 *   2. budget         — Budget and spending rules (R009-R022)
 *   3. naming         — Naming convention rules (R023-R034)
 *   4. date           — Scheduling and date rules (R035-R044)
 *   5. campaign       — Campaign-level setting rules (R045-R060)
 *   6. adset_targeting — Ad set targeting and audience rules (R061-R078)
 *   7. ad             — Ad/creative-level rules (R079-R088)
 *
 * Each entry is a RuleCatalogEntry describing the default configuration
 * for that rule type. Organizations customize instances of these templates
 * via the Admin Portal Rule Builder.
 */

import { EntityLevel, EnforcementMode, Platform, RuleOperator, RuleType } from './enums.js';
import type { RuleCatalogEntry, RuleCategory } from './models.js';

// ─── Category 1: Media Plan (R001–R008) ──────────────────────────────────────

const mediaPlanRules: RuleCatalogEntry[] = [
  {
    catalogId: 'R001',
    name: 'Media Plan ID Required',
    description: 'Every campaign must reference a valid media plan ID in its metadata.',
    category: 'media_plan',
    ruleType: RuleType.MEDIA_PLAN,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'campaign.media_plan_id',
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'error_banner',
      message: 'A media plan ID is required for all campaigns.',
      priority: 1,
    },
    tags: ['media_plan', 'required', 'campaign'],
  },
  {
    catalogId: 'R002',
    name: 'Media Plan Budget Alignment',
    description: 'Campaign budget must not exceed the allocated media plan budget.',
    category: 'media_plan',
    ruleType: RuleType.MEDIA_PLAN,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_EXTERNAL,
    defaultField: 'campaign.budget_value',
    defaultValue: { externalSource: 'media_plan', externalField: 'allocated_budget', comparison: 'less_than_or_equal' },
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'error_banner',
      message: 'Campaign budget exceeds the allocated media plan budget.',
      priority: 1,
    },
    crossEntity: true,
    tags: ['media_plan', 'budget', 'alignment'],
  },
  {
    catalogId: 'R003',
    name: 'Media Plan Flight Dates',
    description: 'Campaign dates must fall within the media plan flight dates.',
    category: 'media_plan',
    ruleType: RuleType.MEDIA_PLAN,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_EXTERNAL,
    defaultField: 'campaign.start_date',
    defaultValue: { externalSource: 'media_plan', externalField: 'flight_start', comparison: 'greater_than_or_equal' },
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'error_banner',
      message: 'Campaign dates must fall within the media plan flight window.',
      priority: 2,
    },
    crossEntity: true,
    tags: ['media_plan', 'dates', 'alignment'],
  },
  {
    catalogId: 'R004',
    name: 'Media Plan Objective Match',
    description: 'Campaign objective must match the media plan objective.',
    category: 'media_plan',
    ruleType: RuleType.MEDIA_PLAN,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.MATCHES_EXTERNAL,
    defaultField: 'campaign.objective',
    defaultValue: { externalSource: 'media_plan', externalField: 'objective' },
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'warning_banner',
      message: 'Campaign objective does not match the media plan objective.',
      priority: 3,
    },
    crossEntity: true,
    tags: ['media_plan', 'objective'],
  },
  {
    catalogId: 'R005',
    name: 'Media Plan Market Alignment',
    description: 'Campaign targeting must align with the media plan market specification.',
    category: 'media_plan',
    ruleType: RuleType.MEDIA_PLAN,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.MATCHES_EXTERNAL,
    defaultField: 'campaign.market',
    defaultValue: { externalSource: 'media_plan', externalField: 'market' },
    uiHints: {
      injectionPoint: 'targeting_location',
      style: 'warning_banner',
      message: 'Campaign market does not match the media plan.',
      priority: 3,
    },
    crossEntity: true,
    tags: ['media_plan', 'market', 'targeting'],
  },
  {
    catalogId: 'R006',
    name: 'Media Plan Platform Match',
    description: 'Campaign platform must match the designated media plan platform.',
    category: 'media_plan',
    ruleType: RuleType.MEDIA_PLAN,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_EXTERNAL,
    defaultField: 'campaign.platform',
    defaultValue: { externalSource: 'media_plan', externalField: 'platform' },
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'error_banner',
      message: 'Campaign is on a platform not specified in the media plan.',
      priority: 1,
    },
    crossEntity: true,
    tags: ['media_plan', 'platform'],
  },
  {
    catalogId: 'R007',
    name: 'Media Plan KPI Target',
    description: 'Campaign optimization goal must align with media plan KPI targets.',
    category: 'media_plan',
    ruleType: RuleType.MEDIA_PLAN,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.MATCHES_EXTERNAL,
    defaultField: 'campaign.optimization_goal',
    defaultValue: { externalSource: 'media_plan', externalField: 'kpi_target' },
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'warning_banner',
      message: 'Campaign optimization goal does not align with media plan KPI.',
      priority: 4,
    },
    crossEntity: true,
    tags: ['media_plan', 'kpi', 'optimization'],
  },
  {
    catalogId: 'R008',
    name: 'Media Plan Approval Required',
    description: 'Campaigns spending above the media plan threshold require second approval.',
    category: 'media_plan',
    ruleType: RuleType.CONFIRMATION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.SECOND_APPROVER,
    defaultOperator: RuleOperator.GREATER_THAN,
    defaultField: 'campaign.budget_value',
    defaultValue: 50000,
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'error_banner',
      message: 'Budget exceeds threshold — second approver required.',
      priority: 1,
    },
    tags: ['media_plan', 'approval', 'budget'],
  },
];

// ─── Category 2: Budget (R009–R022) ──────────────────────────────────────────

const budgetRules: RuleCatalogEntry[] = [
  {
    catalogId: 'R009',
    name: 'Lifetime Budget Required',
    description: 'Campaign must use a lifetime budget (not daily).',
    category: 'budget',
    ruleType: RuleType.BUDGET_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.EQUALS,
    defaultField: 'campaign.budget_type',
    defaultValue: 'lifetime',
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'error_banner',
      message: 'Campaign must use a lifetime budget.',
      priority: 1,
    },
    tags: ['budget', 'lifetime', 'meta'],
  },
  {
    catalogId: 'R010',
    name: 'Daily Budget Required',
    description: 'Campaign must use a daily budget.',
    category: 'budget',
    ruleType: RuleType.BUDGET_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.EQUALS,
    defaultField: 'campaign.budget_type',
    defaultValue: 'daily',
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'error_banner',
      message: 'Campaign must use a daily budget.',
      priority: 1,
    },
    tags: ['budget', 'daily', 'google'],
  },
  {
    catalogId: 'R011',
    name: 'Minimum Campaign Budget',
    description: 'Campaign budget must meet the minimum threshold.',
    category: 'budget',
    ruleType: RuleType.SPENDING_LIMIT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.GREATER_THAN_OR_EQUAL,
    defaultField: 'campaign.budget_value',
    defaultValue: 100,
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'error_banner',
      message: 'Campaign budget must be at least $100.',
      priority: 2,
    },
    tags: ['budget', 'minimum', 'spending'],
  },
  {
    catalogId: 'R012',
    name: 'Maximum Campaign Budget',
    description: 'Campaign budget must not exceed the maximum threshold.',
    category: 'budget',
    ruleType: RuleType.SPENDING_LIMIT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.LESS_THAN_OR_EQUAL,
    defaultField: 'campaign.budget_value',
    defaultValue: 100000,
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'error_banner',
      message: 'Campaign budget must not exceed $100,000.',
      priority: 2,
    },
    tags: ['budget', 'maximum', 'spending'],
  },
  {
    catalogId: 'R013',
    name: 'Budget Range Enforcement',
    description: 'Campaign budget must be within the configured range.',
    category: 'budget',
    ruleType: RuleType.BUDGET_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IN_RANGE,
    defaultField: 'campaign.budget_value',
    defaultValue: { min: 100, max: 100000 },
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'error_banner',
      message: 'Campaign budget must be between $100 and $100,000.',
      priority: 2,
    },
    tags: ['budget', 'range'],
  },
  {
    catalogId: 'R014',
    name: 'CBO Required',
    description: 'Campaign must use Campaign Budget Optimization (Advantage+).',
    category: 'budget',
    ruleType: RuleType.BIDDING_STRATEGY,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.EQUALS,
    defaultField: 'campaign.cbo_enabled',
    defaultValue: true,
    uiHints: {
      injectionPoint: 'cbo_toggle',
      style: 'warning_banner',
      message: 'Campaign Budget Optimization (Advantage+) should be enabled.',
      priority: 3,
    },
    tags: ['budget', 'cbo', 'meta', 'optimization'],
  },
  {
    catalogId: 'R015',
    name: 'Bid Cap Required',
    description: 'Ad set must have a bid cap set when using manual bidding.',
    category: 'budget',
    ruleType: RuleType.BID_VALUE,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.bid_cap',
    uiHints: {
      injectionPoint: 'bidding_section',
      style: 'error_banner',
      message: 'A bid cap must be set when using manual bidding.',
      priority: 2,
    },
    tags: ['budget', 'bid_cap', 'manual_bidding'],
  },
  {
    catalogId: 'R016',
    name: 'Bid Cap Maximum',
    description: 'Bid cap must not exceed the maximum threshold.',
    category: 'budget',
    ruleType: RuleType.BID_VALUE,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.LESS_THAN_OR_EQUAL,
    defaultField: 'ad_set.bid_cap',
    defaultValue: 50,
    uiHints: {
      injectionPoint: 'bidding_section',
      style: 'error_banner',
      message: 'Bid cap must not exceed $50.',
      priority: 2,
    },
    tags: ['budget', 'bid_cap', 'maximum'],
  },
  {
    catalogId: 'R017',
    name: 'Spending Limit Set',
    description: 'Campaign must have an account spending limit configured.',
    category: 'budget',
    ruleType: RuleType.SPENDING_LIMIT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'campaign.spending_limit',
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'warning_banner',
      message: 'Consider setting an account spending limit.',
      priority: 4,
    },
    tags: ['budget', 'spending_limit'],
  },
  {
    catalogId: 'R018',
    name: 'Budget Confirmation Required',
    description: 'Budgets above the threshold require re-confirmation.',
    category: 'budget',
    ruleType: RuleType.CONFIRMATION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.COMMENT_REQUIRED,
    defaultOperator: RuleOperator.GREATER_THAN,
    defaultField: 'campaign.budget_value',
    defaultValue: 10000,
    uiHints: {
      injectionPoint: 'budget_section',
      style: 'warning_banner',
      message: 'Budget exceeds $10,000 — please confirm the amount.',
      priority: 2,
    },
    tags: ['budget', 'confirmation', 'threshold'],
  },
  {
    catalogId: 'R019',
    name: 'Billing Event Enforcement',
    description: 'Ad set must use the specified billing event.',
    category: 'budget',
    ruleType: RuleType.BILLING_EVENT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.EQUALS,
    defaultField: 'ad_set.billing_event',
    defaultValue: 'IMPRESSIONS',
    uiHints: {
      injectionPoint: 'bidding_section',
      style: 'warning_banner',
      message: 'Billing event should be set to Impressions.',
      priority: 3,
    },
    tags: ['budget', 'billing_event'],
  },
  {
    catalogId: 'R020',
    name: 'Performance Goal Required',
    description: 'Ad set must have a performance goal configured.',
    category: 'budget',
    ruleType: RuleType.PERFORMANCE_GOAL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.optimization_goal',
    uiHints: {
      injectionPoint: 'bidding_section',
      style: 'error_banner',
      message: 'A performance goal must be configured.',
      priority: 2,
    },
    tags: ['budget', 'performance', 'optimization'],
  },
  {
    catalogId: 'R021',
    name: 'Cost Per Result Goal',
    description: 'Cost per result goal must be within the acceptable range.',
    category: 'budget',
    ruleType: RuleType.PERFORMANCE_GOAL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IN_RANGE,
    defaultField: 'ad_set.cost_per_result_goal',
    defaultValue: { min: 0.5, max: 100 },
    uiHints: {
      injectionPoint: 'bidding_section',
      style: 'warning_banner',
      message: 'Cost per result goal should be between $0.50 and $100.',
      priority: 3,
    },
    tags: ['budget', 'cost_per_result', 'performance'],
  },
  {
    catalogId: 'R022',
    name: 'ROAS Goal Minimum',
    description: 'ROAS goal must meet the minimum threshold.',
    category: 'budget',
    ruleType: RuleType.PERFORMANCE_GOAL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.GREATER_THAN_OR_EQUAL,
    defaultField: 'ad_set.roas_goal',
    defaultValue: 2.0,
    uiHints: {
      injectionPoint: 'bidding_section',
      style: 'warning_banner',
      message: 'ROAS goal should be at least 2.0x.',
      priority: 3,
    },
    tags: ['budget', 'roas', 'performance'],
  },
];

// ─── Category 3: Naming (R023–R034) ─────────────────────────────────────────

const namingRules: RuleCatalogEntry[] = [
  {
    catalogId: 'R023',
    name: 'Campaign Name Convention',
    description: 'Campaign name must follow the organization naming template.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_TEMPLATE,
    defaultField: 'campaign.name',
    defaultValue: { templateId: 'auto' },
    uiHints: {
      injectionPoint: 'name_field',
      style: 'naming_template_preview',
      message: 'Campaign name must follow the template.',
      priority: 1,
    },
    tags: ['naming', 'campaign', 'template', 'meta'],
  },
  {
    catalogId: 'R024',
    name: 'Ad Set Name Convention',
    description: 'Ad set name must follow the organization naming template.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_TEMPLATE,
    defaultField: 'ad_set.name',
    defaultValue: { templateId: 'auto' },
    uiHints: {
      injectionPoint: 'name_field',
      style: 'naming_template_preview',
      message: 'Ad set name must follow the template.',
      priority: 1,
    },
    tags: ['naming', 'ad_set', 'template', 'meta'],
  },
  {
    catalogId: 'R025',
    name: 'Ad Name Convention',
    description: 'Ad name must follow the organization naming template.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_TEMPLATE,
    defaultField: 'ad.name',
    defaultValue: { templateId: 'auto' },
    uiHints: {
      injectionPoint: 'name_field',
      style: 'naming_template_preview',
      message: 'Ad name must follow the template.',
      priority: 1,
    },
    tags: ['naming', 'ad', 'template', 'meta'],
  },
  {
    catalogId: 'R026',
    name: 'Google Campaign Name Convention',
    description: 'Google Ads campaign name must follow the naming template.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_TEMPLATE,
    defaultField: 'campaign.name',
    defaultValue: { templateId: 'auto' },
    uiHints: {
      injectionPoint: 'name_field',
      style: 'naming_template_preview',
      message: 'Campaign name must follow the Google Ads template.',
      priority: 1,
    },
    tags: ['naming', 'campaign', 'template', 'google'],
  },
  {
    catalogId: 'R027',
    name: 'Google Ad Group Name Convention',
    description: 'Google Ads ad group name must follow the naming template.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_TEMPLATE,
    defaultField: 'ad_set.name',
    defaultValue: { templateId: 'auto' },
    uiHints: {
      injectionPoint: 'name_field',
      style: 'naming_template_preview',
      message: 'Ad group name must follow the Google Ads template.',
      priority: 1,
    },
    tags: ['naming', 'ad_set', 'template', 'google'],
  },
  {
    catalogId: 'R028',
    name: 'Name Must Include Region Code',
    description: 'Entity name must include a valid region code.',
    category: 'naming',
    ruleType: RuleType.TAXONOMY_COMPLIANCE,
    defaultEntityLevels: [EntityLevel.CAMPAIGN, EntityLevel.AD_SET],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.MATCHES_PATTERN,
    defaultField: 'campaign.name',
    defaultValue: '^(NA|EMEA|APAC|LATAM)_',
    uiHints: {
      injectionPoint: 'name_field',
      style: 'warning_banner',
      message: 'Name should start with a valid region code (NA, EMEA, APAC, LATAM).',
      priority: 2,
    },
    tags: ['naming', 'region', 'taxonomy'],
  },
  {
    catalogId: 'R029',
    name: 'Name Must Include Date',
    description: 'Entity name must include a date in YYYYMMDD format.',
    category: 'naming',
    ruleType: RuleType.TAXONOMY_COMPLIANCE,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.MATCHES_PATTERN,
    defaultField: 'campaign.name',
    defaultValue: '\\d{8}',
    uiHints: {
      injectionPoint: 'name_field',
      style: 'warning_banner',
      message: 'Name should include a date in YYYYMMDD format.',
      priority: 3,
    },
    tags: ['naming', 'date', 'taxonomy'],
  },
  {
    catalogId: 'R030',
    name: 'No Special Characters in Name',
    description: 'Entity name must not contain special characters other than _ and -.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN, EntityLevel.AD_SET, EntityLevel.AD],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.MATCHES_PATTERN,
    defaultField: 'campaign.name',
    defaultValue: '^[A-Za-z0-9_\\-\\s]+$',
    uiHints: {
      injectionPoint: 'name_field',
      style: 'warning_banner',
      message: 'Name should only contain letters, numbers, spaces, underscores, and hyphens.',
      priority: 3,
    },
    tags: ['naming', 'validation', 'characters'],
  },
  {
    catalogId: 'R031',
    name: 'Name Maximum Length',
    description: 'Entity name must not exceed the maximum character limit.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN, EntityLevel.AD_SET, EntityLevel.AD],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.LESS_THAN_OR_EQUAL,
    defaultField: 'campaign.name.length',
    defaultValue: 100,
    uiHints: {
      injectionPoint: 'name_field',
      style: 'warning_banner',
      message: 'Name should not exceed 100 characters.',
      priority: 4,
    },
    tags: ['naming', 'length', 'validation'],
  },
  {
    catalogId: 'R032',
    name: 'Name Minimum Length',
    description: 'Entity name must have a minimum number of characters.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN, EntityLevel.AD_SET, EntityLevel.AD],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.GREATER_THAN_OR_EQUAL,
    defaultField: 'campaign.name.length',
    defaultValue: 10,
    uiHints: {
      injectionPoint: 'name_field',
      style: 'warning_banner',
      message: 'Name should have at least 10 characters.',
      priority: 4,
    },
    tags: ['naming', 'length', 'validation'],
  },
  {
    catalogId: 'R033',
    name: 'Name Must Not Be Generic',
    description: 'Entity name must not be a generic or placeholder name.',
    category: 'naming',
    ruleType: RuleType.NAMING_CONVENTION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN, EntityLevel.AD_SET, EntityLevel.AD],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.NOT_CONTAINS,
    defaultField: 'campaign.name',
    defaultValue: ['test', 'temp', 'copy', 'untitled', 'draft'],
    uiHints: {
      injectionPoint: 'name_field',
      style: 'warning_banner',
      message: 'Name should not contain generic terms (test, temp, copy, untitled, draft).',
      priority: 3,
    },
    tags: ['naming', 'quality', 'validation'],
  },
  {
    catalogId: 'R034',
    name: 'Taxonomy Segment Compliance',
    description: 'Each naming segment must use values from the approved taxonomy.',
    category: 'naming',
    ruleType: RuleType.TAXONOMY_COMPLIANCE,
    defaultEntityLevels: [EntityLevel.CAMPAIGN, EntityLevel.AD_SET],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MATCHES_TEMPLATE,
    defaultField: 'campaign.name',
    defaultValue: { templateId: 'auto', strictTaxonomy: true },
    uiHints: {
      injectionPoint: 'name_field',
      style: 'error_banner',
      message: 'All naming segments must use approved taxonomy values.',
      priority: 1,
    },
    tags: ['naming', 'taxonomy', 'compliance'],
  },
];

// ─── Category 4: Date (R035–R044) ───────────────────────────────────────────

const dateRules: RuleCatalogEntry[] = [
  {
    catalogId: 'R035',
    name: 'End Date Required',
    description: 'Ad set must have an end date configured.',
    category: 'date',
    ruleType: RuleType.SCHEDULE_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.COMMENT_REQUIRED,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.schedule.end_date',
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'warning_banner',
      message: 'Ad set should have an end date. Leave a comment if open-ended.',
      priority: 2,
    },
    tags: ['date', 'end_date', 'schedule'],
  },
  {
    catalogId: 'R036',
    name: 'Start Date Not in Past',
    description: 'Campaign start date must not be in the past.',
    category: 'date',
    ruleType: RuleType.SCHEDULE_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.GREATER_THAN_OR_EQUAL,
    defaultField: 'campaign.start_date',
    defaultValue: 'today',
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'error_banner',
      message: 'Start date cannot be in the past.',
      priority: 1,
    },
    tags: ['date', 'start_date', 'validation'],
  },
  {
    catalogId: 'R037',
    name: 'Maximum Campaign Duration',
    description: 'Campaign duration must not exceed the maximum days allowed.',
    category: 'date',
    ruleType: RuleType.DURATION_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.LESS_THAN_OR_EQUAL,
    defaultField: 'campaign.duration_days',
    defaultValue: 90,
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'warning_banner',
      message: 'Campaign duration should not exceed 90 days.',
      priority: 3,
    },
    tags: ['date', 'duration', 'maximum'],
  },
  {
    catalogId: 'R038',
    name: 'Minimum Campaign Duration',
    description: 'Campaign must run for at least the minimum number of days.',
    category: 'date',
    ruleType: RuleType.DURATION_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.GREATER_THAN_OR_EQUAL,
    defaultField: 'campaign.duration_days',
    defaultValue: 7,
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'warning_banner',
      message: 'Campaign should run for at least 7 days.',
      priority: 3,
    },
    tags: ['date', 'duration', 'minimum'],
  },
  {
    catalogId: 'R039',
    name: 'Day Parting Schedule',
    description: 'Ad set must have a day-parting schedule configured.',
    category: 'date',
    ruleType: RuleType.DAY_SCHEDULING,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.dayparting_schedule',
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'warning_banner',
      message: 'Consider configuring a day-parting schedule for optimal delivery.',
      priority: 4,
    },
    tags: ['date', 'dayparting', 'schedule'],
  },
  {
    catalogId: 'R040',
    name: 'No Weekend Launches',
    description: 'Campaign start date must not fall on a weekend.',
    category: 'date',
    ruleType: RuleType.SCHEDULE_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.NOT_EQUALS,
    defaultField: 'campaign.start_day_of_week',
    defaultValue: ['Saturday', 'Sunday'],
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'warning_banner',
      message: 'Campaigns should not launch on weekends.',
      priority: 4,
    },
    tags: ['date', 'weekend', 'schedule'],
  },
  {
    catalogId: 'R041',
    name: 'Minimum Lead Time',
    description: 'Campaign must be created at least 48 hours before its start date.',
    category: 'date',
    ruleType: RuleType.SCHEDULE_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.GREATER_THAN_OR_EQUAL,
    defaultField: 'campaign.lead_time_hours',
    defaultValue: 48,
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'warning_banner',
      message: 'Campaign should be created at least 48 hours before launch.',
      priority: 3,
    },
    tags: ['date', 'lead_time', 'planning'],
  },
  {
    catalogId: 'R042',
    name: 'Google Ads End Date Required',
    description: 'Google Ads campaigns must have an end date.',
    category: 'date',
    ruleType: RuleType.SCHEDULE_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.COMMENT_REQUIRED,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'campaign.end_date',
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'warning_banner',
      message: 'Google Ads campaigns should have an end date configured.',
      priority: 2,
    },
    tags: ['date', 'end_date', 'google'],
  },
  {
    catalogId: 'R043',
    name: 'Ad Set Schedule Matches Campaign',
    description: 'Ad set schedule must fall within the parent campaign dates.',
    category: 'date',
    ruleType: RuleType.SCHEDULE_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.CROSS_ENTITY_EQUALS,
    defaultField: 'ad_set.schedule',
    defaultValue: { sourceEntity: 'ad_set', targetEntity: 'campaign', comparison: 'within_range' },
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'error_banner',
      message: 'Ad set dates must fall within the campaign date range.',
      priority: 1,
    },
    crossEntity: true,
    tags: ['date', 'schedule', 'cross_entity'],
  },
  {
    catalogId: 'R044',
    name: 'Timezone Consistency',
    description: 'Campaign timezone must match the ad account timezone setting.',
    category: 'date',
    ruleType: RuleType.SCHEDULE_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.CROSS_ENTITY_EQUALS,
    defaultField: 'campaign.timezone',
    defaultValue: { sourceEntity: 'campaign', targetEntity: 'account', targetField: 'timezone' },
    uiHints: {
      injectionPoint: 'schedule_section',
      style: 'warning_banner',
      message: 'Campaign timezone should match the ad account timezone.',
      priority: 4,
    },
    crossEntity: true,
    tags: ['date', 'timezone', 'consistency'],
  },
];

// ─── Category 5: Campaign (R045–R060) ───────────────────────────────────────

const campaignRules: RuleCatalogEntry[] = [
  {
    catalogId: 'R045',
    name: 'Campaign Objective Required',
    description: 'Campaign must have a valid objective selected.',
    category: 'campaign',
    ruleType: RuleType.CUSTOM_FIELD,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'campaign.objective',
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'error_banner',
      message: 'A campaign objective must be selected.',
      priority: 1,
    },
    tags: ['campaign', 'objective', 'required'],
  },
  {
    catalogId: 'R046',
    name: 'Allowed Objectives',
    description: 'Campaign objective must be from the approved list.',
    category: 'campaign',
    ruleType: RuleType.CUSTOM_FIELD,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_ONLY_BE,
    defaultField: 'campaign.objective',
    defaultValue: ['CONVERSIONS', 'LEAD_GENERATION', 'BRAND_AWARENESS', 'REACH', 'TRAFFIC'],
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'error_banner',
      message: 'Campaign objective must be from the approved list.',
      priority: 1,
    },
    tags: ['campaign', 'objective', 'whitelist'],
  },
  {
    catalogId: 'R047',
    name: 'Special Ad Categories Required',
    description: 'Campaigns in regulated industries must declare special ad categories.',
    category: 'campaign',
    ruleType: RuleType.SPECIAL_AD_CATEGORIES,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'campaign.special_ad_categories',
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'error_banner',
      message: 'Special ad categories must be declared for regulated industries.',
      priority: 1,
    },
    tags: ['campaign', 'special_ad_categories', 'compliance'],
  },
  {
    catalogId: 'R048',
    name: 'Special Ad Categories Whitelist',
    description: 'Special ad categories must be from the approved list.',
    category: 'campaign',
    ruleType: RuleType.SPECIAL_AD_CATEGORIES,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_ONLY_BE,
    defaultField: 'campaign.special_ad_categories',
    defaultValue: ['CREDIT', 'EMPLOYMENT', 'HOUSING', 'SOCIAL_ISSUES_ELECTIONS_POLITICS'],
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'error_banner',
      message: 'Special ad categories must be from the approved list.',
      priority: 1,
    },
    tags: ['campaign', 'special_ad_categories', 'whitelist'],
  },
  {
    catalogId: 'R049',
    name: 'Campaign Status Enforcement',
    description: 'New campaigns must be created in PAUSED status.',
    category: 'campaign',
    ruleType: RuleType.STATUS_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.EQUALS,
    defaultField: 'campaign.status',
    defaultValue: 'PAUSED',
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'error_banner',
      message: 'New campaigns must be created in PAUSED status.',
      priority: 1,
    },
    tags: ['campaign', 'status', 'paused'],
  },
  {
    catalogId: 'R050',
    name: 'Facebook Page Required',
    description: 'Campaign must be associated with an approved Facebook Page.',
    category: 'campaign',
    ruleType: RuleType.IDENTITY_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad.facebook_page_id',
    uiHints: {
      injectionPoint: 'identity_section',
      style: 'error_banner',
      message: 'A Facebook Page must be selected.',
      priority: 1,
    },
    tags: ['campaign', 'identity', 'facebook_page'],
  },
  {
    catalogId: 'R051',
    name: 'Instagram Account Required',
    description: 'Ads on Instagram must have an Instagram account linked.',
    category: 'campaign',
    ruleType: RuleType.IDENTITY_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad.instagram_account_id',
    uiHints: {
      injectionPoint: 'identity_section',
      style: 'error_banner',
      message: 'An Instagram account must be linked for Instagram placements.',
      priority: 1,
    },
    tags: ['campaign', 'identity', 'instagram'],
  },
  {
    catalogId: 'R052',
    name: 'Approved Facebook Pages Only',
    description: 'Facebook Page must be from the approved list.',
    category: 'campaign',
    ruleType: RuleType.IDENTITY_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_ONLY_BE,
    defaultField: 'ad.facebook_page_id',
    defaultValue: [],
    uiHints: {
      injectionPoint: 'identity_section',
      style: 'error_banner',
      message: 'Only approved Facebook Pages may be used.',
      priority: 1,
    },
    tags: ['campaign', 'identity', 'whitelist'],
  },
  {
    catalogId: 'R053',
    name: 'Pixel Required',
    description: 'Campaign must have a tracking pixel configured.',
    category: 'campaign',
    ruleType: RuleType.PIXEL_CONVERSION,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.pixel_id',
    uiHints: {
      injectionPoint: 'tracking_section',
      style: 'error_banner',
      message: 'A tracking pixel must be configured.',
      priority: 1,
    },
    tags: ['campaign', 'pixel', 'tracking'],
  },
  {
    catalogId: 'R054',
    name: 'Conversion Event Required',
    description: 'Ad set must have a conversion event selected when using conversion objective.',
    category: 'campaign',
    ruleType: RuleType.PIXEL_CONVERSION,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.conversion_event',
    uiHints: {
      injectionPoint: 'tracking_section',
      style: 'error_banner',
      message: 'A conversion event must be selected.',
      priority: 1,
    },
    tags: ['campaign', 'conversion', 'pixel'],
  },
  {
    catalogId: 'R055',
    name: 'Approved Pixels Only',
    description: 'Only approved pixel IDs may be used.',
    category: 'campaign',
    ruleType: RuleType.PIXEL_CONVERSION,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_ONLY_BE,
    defaultField: 'ad_set.pixel_id',
    defaultValue: [],
    uiHints: {
      injectionPoint: 'tracking_section',
      style: 'error_banner',
      message: 'Only approved pixel IDs may be used.',
      priority: 1,
    },
    tags: ['campaign', 'pixel', 'whitelist'],
  },
  {
    catalogId: 'R056',
    name: 'Google Conversion Tracking Required',
    description: 'Google Ads campaigns must have conversion tracking configured.',
    category: 'campaign',
    ruleType: RuleType.TRACKING_VALIDATION,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'campaign.conversion_actions',
    uiHints: {
      injectionPoint: 'tracking_section',
      style: 'error_banner',
      message: 'Conversion tracking must be configured for Google Ads campaigns.',
      priority: 1,
    },
    tags: ['campaign', 'conversion', 'google', 'tracking'],
  },
  {
    catalogId: 'R057',
    name: 'UTM Tracking URL Required',
    description: 'Ad destination URL must include UTM parameters.',
    category: 'campaign',
    ruleType: RuleType.TRACKING_URL,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.CONTAINS,
    defaultField: 'ad.destination_url',
    defaultValue: 'utm_',
    uiHints: {
      injectionPoint: 'url_section',
      style: 'warning_banner',
      message: 'Destination URL should include UTM tracking parameters.',
      priority: 2,
    },
    tags: ['campaign', 'tracking', 'utm', 'url'],
  },
  {
    catalogId: 'R058',
    name: 'Valid Destination URL',
    description: 'Ad destination URL must be a valid HTTPS URL.',
    category: 'campaign',
    ruleType: RuleType.TRACKING_URL,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_VALID_URL,
    defaultField: 'ad.destination_url',
    uiHints: {
      injectionPoint: 'url_section',
      style: 'error_banner',
      message: 'Destination URL must be a valid HTTPS URL.',
      priority: 1,
    },
    tags: ['campaign', 'url', 'validation'],
  },
  {
    catalogId: 'R059',
    name: 'EU Transparency Required',
    description: 'Campaigns targeting EU countries must have beneficiary and payer declared.',
    category: 'campaign',
    ruleType: RuleType.EU_COMPLIANCE,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.AND,
    defaultField: 'campaign.eu_transparency',
    defaultValue: {
      conditions: [
        { field: 'campaign.eu_transparency.beneficiary', operator: 'is_set' },
        { field: 'campaign.eu_transparency.payer', operator: 'is_set' },
      ],
    },
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'error_banner',
      message: 'EU campaigns must declare beneficiary and payer information.',
      priority: 1,
    },
    tags: ['campaign', 'eu', 'compliance', 'transparency'],
  },
  {
    catalogId: 'R060',
    name: 'Campaign Label Required',
    description: 'Campaign must have at least one label/tag applied.',
    category: 'campaign',
    ruleType: RuleType.CUSTOM_FIELD,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'campaign.labels',
    uiHints: {
      injectionPoint: 'campaign_details',
      style: 'warning_banner',
      message: 'Campaign should have at least one label applied for organization.',
      priority: 4,
    },
    tags: ['campaign', 'labels', 'organization'],
  },
];

// ─── Category 6: Ad Set Targeting (R061–R078) ───────────────────────────────

const adsetTargetingRules: RuleCatalogEntry[] = [
  {
    catalogId: 'R061',
    name: 'Must Target Country',
    description: 'Ad set must target at least one specified country.',
    category: 'adset_targeting',
    ruleType: RuleType.TARGETING_CONSTRAINT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_INCLUDE,
    defaultField: 'ad_set.targeting.geo_locations.countries',
    defaultValue: ['US'],
    uiHints: {
      injectionPoint: 'targeting_location',
      style: 'error_banner',
      message: 'Ad set must target the specified country.',
      priority: 1,
    },
    tags: ['targeting', 'geo', 'country'],
  },
  {
    catalogId: 'R062',
    name: 'Country Exclusion',
    description: 'Ad set must exclude specified countries.',
    category: 'adset_targeting',
    ruleType: RuleType.TARGETING_CONSTRAINT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_EXCLUDE,
    defaultField: 'ad_set.targeting.geo_locations.countries',
    defaultValue: [],
    uiHints: {
      injectionPoint: 'targeting_location',
      style: 'error_banner',
      message: 'Ad set must not target the excluded countries.',
      priority: 1,
    },
    tags: ['targeting', 'geo', 'exclusion'],
  },
  {
    catalogId: 'R063',
    name: 'Country Restriction',
    description: 'Ad set must target only the specified countries.',
    category: 'adset_targeting',
    ruleType: RuleType.TARGETING_CONSTRAINT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_ONLY_BE,
    defaultField: 'ad_set.targeting.geo_locations.countries',
    defaultValue: ['US'],
    uiHints: {
      injectionPoint: 'targeting_location',
      style: 'error_banner',
      message: 'Ad set must target only the approved countries.',
      priority: 1,
    },
    tags: ['targeting', 'geo', 'restriction'],
  },
  {
    catalogId: 'R064',
    name: 'Age Range Enforcement',
    description: 'Ad set must target the specified age range.',
    category: 'adset_targeting',
    ruleType: RuleType.TARGETING_CONSTRAINT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IN_RANGE,
    defaultField: 'ad_set.targeting.age_range',
    defaultValue: { min: 18, max: 65 },
    uiHints: {
      injectionPoint: 'targeting_demographics',
      style: 'error_banner',
      message: 'Ad set must target ages 18-65.',
      priority: 2,
    },
    tags: ['targeting', 'age', 'demographics'],
  },
  {
    catalogId: 'R065',
    name: 'Language Targeting Required',
    description: 'Ad set must have at least one language specified.',
    category: 'adset_targeting',
    ruleType: RuleType.TARGETING_CONSTRAINT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.targeting.languages',
    uiHints: {
      injectionPoint: 'targeting_demographics',
      style: 'warning_banner',
      message: 'Language targeting should be specified.',
      priority: 3,
    },
    tags: ['targeting', 'language'],
  },
  {
    catalogId: 'R066',
    name: 'Brand Safety Exclusions',
    description: 'Must exclude specified sensitive content categories.',
    category: 'adset_targeting',
    ruleType: RuleType.BRAND_SAFETY,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_INCLUDE,
    defaultField: 'ad_set.brand_safety.excluded_categories',
    defaultValue: ['Sexual', 'Weapons', 'Gambling'],
    uiHints: {
      injectionPoint: 'brand_safety_section',
      style: 'error_banner',
      message: 'Required brand safety exclusions must be applied.',
      priority: 1,
    },
    tags: ['targeting', 'brand_safety', 'exclusions'],
  },
  {
    catalogId: 'R067',
    name: 'Placement Control - Feed Only',
    description: 'Ad set must use only feed placements.',
    category: 'adset_targeting',
    ruleType: RuleType.PLACEMENT_CONTROL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.MUST_ONLY_BE,
    defaultField: 'ad_set.placements',
    defaultValue: ['facebook_feed', 'instagram_feed'],
    uiHints: {
      injectionPoint: 'placement_section',
      style: 'warning_banner',
      message: 'Ad set should use feed-only placements.',
      priority: 3,
    },
    tags: ['targeting', 'placement', 'feed'],
  },
  {
    catalogId: 'R068',
    name: 'Audience Network Exclusion',
    description: 'Ad set must not use Audience Network placement.',
    category: 'adset_targeting',
    ruleType: RuleType.PLACEMENT_CONTROL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_EXCLUDE,
    defaultField: 'ad_set.placements',
    defaultValue: ['audience_network'],
    uiHints: {
      injectionPoint: 'placement_section',
      style: 'error_banner',
      message: 'Audience Network placement must be excluded.',
      priority: 2,
    },
    tags: ['targeting', 'placement', 'audience_network'],
  },
  {
    catalogId: 'R069',
    name: 'Automatic Placements Warning',
    description: 'Warn when using automatic placements instead of manual selection.',
    category: 'adset_targeting',
    ruleType: RuleType.PLACEMENT_ENFORCEMENT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.NOT_EQUALS,
    defaultField: 'ad_set.placement_type',
    defaultValue: 'automatic',
    uiHints: {
      injectionPoint: 'placement_section',
      style: 'warning_banner',
      message: 'Consider using manual placements for better control.',
      priority: 4,
    },
    tags: ['targeting', 'placement', 'automatic'],
  },
  {
    catalogId: 'R070',
    name: 'Custom Audience Required',
    description: 'Ad set must use at least one custom audience.',
    category: 'adset_targeting',
    ruleType: RuleType.AUDIENCE_CONTROL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.targeting.custom_audiences',
    uiHints: {
      injectionPoint: 'targeting_audiences',
      style: 'warning_banner',
      message: 'Consider using custom audiences for better targeting.',
      priority: 3,
    },
    tags: ['targeting', 'audience', 'custom'],
  },
  {
    catalogId: 'R071',
    name: 'Excluded Audiences Required',
    description: 'Ad set must have exclusion audiences configured.',
    category: 'adset_targeting',
    ruleType: RuleType.AUDIENCE_CONTROL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.targeting.excluded_custom_audiences',
    uiHints: {
      injectionPoint: 'targeting_audiences',
      style: 'warning_banner',
      message: 'Consider excluding converted audiences to avoid waste.',
      priority: 3,
    },
    tags: ['targeting', 'audience', 'exclusion'],
  },
  {
    catalogId: 'R072',
    name: 'Frequency Cap Required',
    description: 'Ad set must have a frequency cap configured.',
    category: 'adset_targeting',
    ruleType: RuleType.FREQUENCY_CAP,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.frequency_cap',
    uiHints: {
      injectionPoint: 'delivery_section',
      style: 'warning_banner',
      message: 'Consider setting a frequency cap to prevent ad fatigue.',
      priority: 3,
    },
    tags: ['targeting', 'frequency', 'delivery'],
  },
  {
    catalogId: 'R073',
    name: 'Maximum Frequency Cap',
    description: 'Frequency cap must not exceed the maximum impressions per user.',
    category: 'adset_targeting',
    ruleType: RuleType.FREQUENCY_CAP,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.LESS_THAN_OR_EQUAL,
    defaultField: 'ad_set.frequency_cap.max_impressions',
    defaultValue: 5,
    uiHints: {
      injectionPoint: 'delivery_section',
      style: 'warning_banner',
      message: 'Frequency cap should not exceed 5 impressions per user per day.',
      priority: 3,
    },
    tags: ['targeting', 'frequency', 'maximum'],
  },
  {
    catalogId: 'R074',
    name: 'Inventory Filter Required',
    description: 'Brand safety inventory filter must be configured.',
    category: 'adset_targeting',
    ruleType: RuleType.INVENTORY_FILTER,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad_set.inventory_filter',
    uiHints: {
      injectionPoint: 'brand_safety_section',
      style: 'warning_banner',
      message: 'Consider configuring an inventory filter for brand safety.',
      priority: 3,
    },
    tags: ['targeting', 'inventory', 'brand_safety'],
  },
  {
    catalogId: 'R075',
    name: 'Google Target US Only',
    description: 'Google Ads campaigns must target the United States.',
    category: 'adset_targeting',
    ruleType: RuleType.TARGETING_CONSTRAINT,
    defaultEntityLevels: [EntityLevel.CAMPAIGN],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.MUST_INCLUDE,
    defaultField: 'campaign.geo_targets',
    defaultValue: ['US'],
    uiHints: {
      injectionPoint: 'targeting_location',
      style: 'error_banner',
      message: 'Campaign must target the United States.',
      priority: 1,
    },
    tags: ['targeting', 'geo', 'google', 'us'],
  },
  {
    catalogId: 'R076',
    name: 'Minimum Audience Size',
    description: 'Target audience must meet the minimum estimated reach.',
    category: 'adset_targeting',
    ruleType: RuleType.AUDIENCE_CONTROL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.GREATER_THAN_OR_EQUAL,
    defaultField: 'ad_set.targeting.estimated_reach',
    defaultValue: 10000,
    uiHints: {
      injectionPoint: 'targeting_audiences',
      style: 'warning_banner',
      message: 'Target audience should have at least 10,000 estimated reach.',
      priority: 3,
    },
    tags: ['targeting', 'audience', 'reach', 'minimum'],
  },
  {
    catalogId: 'R077',
    name: 'Lookalike Audience Size',
    description: 'Lookalike audience percentage must be within the approved range.',
    category: 'adset_targeting',
    ruleType: RuleType.AUDIENCE_CONTROL,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IN_RANGE,
    defaultField: 'ad_set.targeting.lookalike_percent',
    defaultValue: { min: 1, max: 5 },
    uiHints: {
      injectionPoint: 'targeting_audiences',
      style: 'warning_banner',
      message: 'Lookalike audience should be between 1-5% for optimal performance.',
      priority: 3,
    },
    tags: ['targeting', 'audience', 'lookalike'],
  },
  {
    catalogId: 'R078',
    name: 'Google Keyword Count',
    description: 'Google Ads ad groups must have a minimum number of keywords.',
    category: 'adset_targeting',
    ruleType: RuleType.TARGETING_CONSTRAINT,
    defaultEntityLevels: [EntityLevel.AD_SET],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.COUNT_IN_RANGE,
    defaultField: 'ad_set.keywords',
    defaultValue: { min: 3, max: 20 },
    uiHints: {
      injectionPoint: 'targeting_keywords',
      style: 'warning_banner',
      message: 'Ad group should have between 3 and 20 keywords.',
      priority: 3,
    },
    tags: ['targeting', 'keywords', 'google', 'count'],
  },
];

// ─── Category 7: Ad (R079–R088) ─────────────────────────────────────────────

const adRules: RuleCatalogEntry[] = [
  {
    catalogId: 'R079',
    name: 'Ad Creative Required',
    description: 'Ad must have at least one creative asset.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_VALIDATION,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad.creative',
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'error_banner',
      message: 'Ad must have a creative asset.',
      priority: 1,
    },
    tags: ['ad', 'creative', 'required'],
  },
  {
    catalogId: 'R080',
    name: 'Primary Text Required',
    description: 'Ad must have primary text content.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_VALIDATION,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad.creative.primary_text',
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'error_banner',
      message: 'Primary text is required.',
      priority: 1,
    },
    tags: ['ad', 'creative', 'text'],
  },
  {
    catalogId: 'R081',
    name: 'Headline Required',
    description: 'Ad must have a headline.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_VALIDATION,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad.creative.headline',
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'error_banner',
      message: 'A headline is required.',
      priority: 1,
    },
    tags: ['ad', 'creative', 'headline'],
  },
  {
    catalogId: 'R082',
    name: 'Headline Maximum Length',
    description: 'Ad headline must not exceed the maximum character limit.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_SPECS,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.LESS_THAN_OR_EQUAL,
    defaultField: 'ad.creative.headline.length',
    defaultValue: 40,
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'error_banner',
      message: 'Headline must not exceed 40 characters.',
      priority: 2,
    },
    tags: ['ad', 'creative', 'headline', 'length'],
  },
  {
    catalogId: 'R083',
    name: 'Primary Text Maximum Length',
    description: 'Ad primary text must not exceed the maximum character limit.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_SPECS,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.LESS_THAN_OR_EQUAL,
    defaultField: 'ad.creative.primary_text.length',
    defaultValue: 125,
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'warning_banner',
      message: 'Primary text should not exceed 125 characters for optimal display.',
      priority: 3,
    },
    tags: ['ad', 'creative', 'text', 'length'],
  },
  {
    catalogId: 'R084',
    name: 'Call to Action Required',
    description: 'Ad must have a call-to-action button selected.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_VALIDATION,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad.creative.call_to_action',
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'warning_banner',
      message: 'A call-to-action button should be selected.',
      priority: 2,
    },
    tags: ['ad', 'creative', 'cta'],
  },
  {
    catalogId: 'R085',
    name: 'Approved CTA Values',
    description: 'Call-to-action must be from the approved list.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_VALIDATION,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.META],
    defaultEnforcement: EnforcementMode.WARNING,
    defaultOperator: RuleOperator.MUST_ONLY_BE,
    defaultField: 'ad.creative.call_to_action',
    defaultValue: ['LEARN_MORE', 'SHOP_NOW', 'SIGN_UP', 'CONTACT_US', 'APPLY_NOW'],
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'warning_banner',
      message: 'Call-to-action should be from the approved list.',
      priority: 3,
    },
    tags: ['ad', 'creative', 'cta', 'whitelist'],
  },
  {
    catalogId: 'R086',
    name: 'Ad Destination URL Required',
    description: 'Ad must have a destination URL configured.',
    category: 'ad',
    ruleType: RuleType.TRACKING_URL,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.ALL],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.IS_SET,
    defaultField: 'ad.destination_url',
    uiHints: {
      injectionPoint: 'url_section',
      style: 'error_banner',
      message: 'A destination URL is required.',
      priority: 1,
    },
    tags: ['ad', 'url', 'required'],
  },
  {
    catalogId: 'R087',
    name: 'Google Responsive Search Ad Headlines',
    description: 'Google RSA must have the required number of headline variations.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_SPECS,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.COUNT_IN_RANGE,
    defaultField: 'ad.creative.headlines',
    defaultValue: { min: 3, max: 15 },
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'error_banner',
      message: 'Responsive Search Ads must have 3-15 headline variations.',
      priority: 1,
    },
    tags: ['ad', 'creative', 'google', 'rsa', 'headlines'],
  },
  {
    catalogId: 'R088',
    name: 'Google RSA Description Count',
    description: 'Google RSA must have the required number of description variations.',
    category: 'ad',
    ruleType: RuleType.CREATIVE_SPECS,
    defaultEntityLevels: [EntityLevel.AD],
    defaultPlatforms: [Platform.GOOGLE_ADS],
    defaultEnforcement: EnforcementMode.BLOCKING,
    defaultOperator: RuleOperator.COUNT_IN_RANGE,
    defaultField: 'ad.creative.descriptions',
    defaultValue: { min: 2, max: 4 },
    uiHints: {
      injectionPoint: 'creative_section',
      style: 'error_banner',
      message: 'Responsive Search Ads must have 2-4 description variations.',
      priority: 1,
    },
    tags: ['ad', 'creative', 'google', 'rsa', 'descriptions'],
  },
];

// ─── Exported Catalog ───────────────────────────────────────────────────────

/**
 * Complete rule catalog with all 88 governance rules.
 * Rules are ordered by catalog ID (R001–R088).
 */
export const RULE_CATALOG: readonly RuleCatalogEntry[] = [
  ...mediaPlanRules,
  ...budgetRules,
  ...namingRules,
  ...dateRules,
  ...campaignRules,
  ...adsetTargetingRules,
  ...adRules,
] as const;

/**
 * All rule categories with their display labels.
 */
export const RULE_CATEGORIES: Record<RuleCategory, string> = {
  media_plan: 'Media Plan',
  budget: 'Budget & Spending',
  naming: 'Naming Conventions',
  date: 'Dates & Scheduling',
  campaign: 'Campaign Settings',
  adset_targeting: 'Ad Set & Targeting',
  ad: 'Ad & Creative',
};

// ─── Lookup Helpers ─────────────────────────────────────────────────────────

/**
 * Look up a single rule catalog entry by its catalog ID.
 *
 * @param catalogId - The catalog identifier, e.g. "R001"
 * @returns The matching catalog entry, or undefined if not found
 */
export function getRuleByCatalogId(catalogId: string): RuleCatalogEntry | undefined {
  return RULE_CATALOG.find((r) => r.catalogId === catalogId);
}

/**
 * Get all rules in a given category.
 *
 * @param category - The category to filter by
 * @returns Array of rules in that category
 */
export function getRulesByCategory(category: RuleCategory): RuleCatalogEntry[] {
  return RULE_CATALOG.filter((r) => r.category === category);
}

/**
 * Get all rules of a given type.
 *
 * @param ruleType - The rule type to filter by
 * @returns Array of rules matching the type
 */
export function getRulesByType(ruleType: RuleType): RuleCatalogEntry[] {
  return RULE_CATALOG.filter((r) => r.ruleType === ruleType);
}

/**
 * Get all rules applicable to a given platform.
 *
 * @param platform - The platform to filter for
 * @returns Array of rules that apply to the platform
 */
export function getRulesByPlatform(platform: Platform): RuleCatalogEntry[] {
  return RULE_CATALOG.filter(
    (r) => r.defaultPlatforms.includes(platform) || r.defaultPlatforms.includes(Platform.ALL)
  );
}

/**
 * Get all rules applicable to a given entity level.
 *
 * @param entityLevel - The entity level to filter for
 * @returns Array of rules that apply to the entity level
 */
export function getRulesByEntityLevel(entityLevel: EntityLevel): RuleCatalogEntry[] {
  return RULE_CATALOG.filter((r) => r.defaultEntityLevels.includes(entityLevel));
}

/**
 * Search rules by tags.
 *
 * @param tags - One or more tags to search for
 * @param matchAll - If true, rule must match ALL tags; if false, ANY tag
 * @returns Matching rules
 */
export function getRulesByTags(tags: string[], matchAll = false): RuleCatalogEntry[] {
  if (matchAll) {
    return RULE_CATALOG.filter((r) => tags.every((t) => r.tags.includes(t)));
  }
  return RULE_CATALOG.filter((r) => tags.some((t) => r.tags.includes(t)));
}

/**
 * Get a count of rules by category.
 *
 * @returns Object mapping each category to its rule count
 */
export function getRuleCounts(): Record<RuleCategory, number> {
  const counts: Record<string, number> = {};
  for (const rule of RULE_CATALOG) {
    counts[rule.category] = (counts[rule.category] ?? 0) + 1;
  }
  return counts as Record<RuleCategory, number>;
}
